#!/usr/bin/env zsh
set -euo pipefail

QUERY=$(rofi -dmenu -p "Search")
VALUE=$(~/.scripts/rofi/rofi-youtube/scraper.js $QUERY)
NAME=$(echo $VALUE | cut -d " " -f 2- | rofi -dmenu -p "Video")
ID=$(echo $VALUE | grep "$NAME" | cut -d " " -f 1)

mpv "https://youtube.com/watch?v=$ID"

